language: elixir
elixir:
- 1.12.3
otp_release:
- 24.0.2
cache:
  directories:
  - _build
  - deps
script:
- mix do deps.get, coveralls.json
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - MIX_ENV=test
  - AUTH_API_KEY=2PzB7PPnpuLsbWmWtXpGyI+kfSQSQ1zUW2Atz/+8PdZuSEJzHgzGnJWV35nTKRwx
